// Generates one static detail page per tour package at the repo root
// (tour-<slug>.html) from templates/tour.html and assets/js/tours-data.js,
// then writes sitemap.xml. Static content (title, meta, route, highlights,
// stops, map) is inlined for SEO; prices stay client-side (tours-pricing.js)
// so a price change needs no rebuild. The custom package is skipped: it
// links to the contact form instead.
//   npm run build:tours

const fs = require('fs');
const path = require('path');
const site = require('./lib/site');
require('./lib/blocks');
const { processImages, preloadLinks } = require('./lib/images');
const map = require('./lib/map');

const { esc, icon, ROOT, ORIGIN, BRAND } = site;
const TEMPLATE = fs.readFileSync(path.join(ROOT, 'templates/tour.html'), 'utf8');
const OUTLINE = fs.readFileSync(path.join(ROOT, 'assets/images/namibia-outline.svg'), 'utf8')
  .match(/\sd="([^"]+)"/)[1];
const GENERATED_NOTE = '<!-- GENERATED by scripts/build-tours.js. Edit templates/tour.html or tours-data.js, not this file. -->';
const WEEKDAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

// Preferred label side for stops that sit close together on the map. dy is
// a baseline nudge in ems, so neighbouring labels don't collide.
const LABEL_SIDE = {
  Sossusvlei: { side: 'left', dy: 0.3 },
  Sesriem: { side: 'right', dy: 0.1 },
  'Walvis Bay': { side: 'left', dy: 0.7 },
  Swakopmund: { side: 'left', dy: -0.3 },
  Twyfelfontein: { side: 'left', dy: 0.4 },
  Damaraland: { side: 'right', dy: -0.2 },
};

// Map framing. The viewBox hugs the route's stops plus 12% padding, but
// never gets smaller than MIN_W x MIN_H map units or thinner than
// MIN_ASPECT, so a two-stop route still reads as a map. Label size and dot
// radius scale with the viewBox width, so every map renders its labels at
// the same on-screen size (about 15px at phone width).
const MAP_PAD = 0.12;
const MIN_W = 340;
const MIN_H = 220;
const MIN_ASPECT = 0.55; // height / width
const FONT_PER_UNIT = 0.045;
const DOT_PER_UNIT = 0.017;
const CHAR_WIDTH_EM = 0.6; // conservative average advance for Inter 600

function fitViewBox(points) {
  const xs = points.map((p) => p.x);
  const ys = points.map((p) => p.y);
  const minX = Math.min(...xs);
  const maxX = Math.max(...xs);
  const minY = Math.min(...ys);
  const maxY = Math.max(...ys);
  const spanX = maxX - minX;
  const spanY = maxY - minY;
  let w = Math.max(spanX * (1 + 2 * MAP_PAD), MIN_W);
  let h = Math.max(spanY * (1 + 2 * MAP_PAD), MIN_H, w * MIN_ASPECT);
  w = Math.max(w, h * 0.8);
  const cx = (minX + maxX) / 2;
  const cy = (minY + maxY) / 2;
  const r1 = (v) => Math.round(v * 10) / 10;
  return { x: r1(cx - w / 2), y: r1(cy - h / 2), w: r1(w), h: r1(h) };
}

// Puts a label beside its dot on the preferred side, flips it when that
// side would overflow the viewBox, and clamps it inside as a last resort.
// Returns the label's left edge, so text-anchor is always "start".
function placeLabel(name, dot, vb, font, gap) {
  const pref = LABEL_SIDE[name] || { side: 'right', dy: 0.35 };
  const width = name.length * font * CHAR_WIDTH_EM;
  const margin = font * 0.3;
  const left = vb.x + margin;
  const right = vb.x + vb.w - margin;
  const at = (side) => (side === 'left' ? dot.x - gap - width : dot.x + gap);
  const fits = (x) => x >= left && x + width <= right;
  let x = at(pref.side);
  if (!fits(x)) {
    const flipped = at(pref.side === 'left' ? 'right' : 'left');
    x = fits(flipped) ? flipped : Math.min(Math.max(x, left), right - width);
  }
  const ascent = font * 0.8;
  const descent = font * 0.25;
  let y = dot.y + pref.dy * font;
  y = Math.min(Math.max(y, vb.y + margin + ascent), vb.y + vb.h - margin - descent);
  const r1 = (v) => Math.round(v * 10) / 10;
  return { x: r1(x), y: r1(y) };
}

const listJoin = (items) => (items.length < 2 ? items.join('')
  : `${items.slice(0, -1).join(', ')} and ${items[items.length - 1]}`);
const uniqueStops = (pkg) => pkg.stops.filter((s, i, all) => all.findIndex((o) => o.name === s.name) === i);
const tourFile = (pkg) => `tour-${pkg.slug}.html`;

function describe(pkg) {
  const places = uniqueStops(pkg).map((s) => s.name);
  return `${pkg.name} with ${BRAND}: ${pkg.duration} days through ${listJoin(places)}. Highlights include ${listJoin(pkg.highlights.slice(0, 3)).toLowerCase()}.`;
}

// ---------------------------------------------------------------- blocks
function registerTourBlocks() {
  site.registerBlock('tour-preload', (page) => `\n${preloadLinks(page.tour.image.src)}\n`);

  site.registerBlock('tour-jsonld', (page) => {
    const pkg = page.tour;
    const data = {
      '@context': 'https://schema.org',
      '@type': 'TouristTrip',
      name: pkg.name,
      description: page.description,
      url: `${ORIGIN}/${page.file}`,
      image: `${ORIGIN}/${pkg.image.src}`,
      provider: { '@type': 'TravelAgency', name: BRAND, url: `${ORIGIN}/` },
      itinerary: {
        '@type': 'ItemList',
        itemListElement: pkg.stops.map((s, i) => ({
          '@type': 'ListItem',
          position: i + 1,
          item: { '@type': 'Place', name: s.name, geo: { '@type': 'GeoCoordinates', latitude: s.lat, longitude: s.lng } },
        })),
      },
    };
    if (pkg.priceConfirmed && pkg.price != null) {
      data.offers = { '@type': 'Offer', price: pkg.price, priceCurrency: 'NAD', url: `${ORIGIN}/${page.file}` };
    }
    return `\n<script type="application/ld+json">\n${JSON.stringify(data, null, 2)}\n</script>\n`;
  });

  site.registerBlock('tour-gallery', (page) => {
    const images = page.tour.gallery.slice(0, 3);
    const item = (img, i, cls) => `
      <button type="button" class="gallery-item ${cls}" data-gallery-index="${i}" aria-label="View photo ${i + 1} of ${images.length}: ${esc(img.alt)}">
        <img src="${img.src}" alt="${esc(img.alt)}" sizes="${i === 0 ? '(max-width: 760px) 100vw, 66vw' : '(max-width: 760px) 50vw, 33vw'}" ${i === 0 ? 'fetchpriority="high" loading="eager"' : 'loading="lazy"'} decoding="async">
        ${img.credit ? `<span class="photo-credit">Photo: ${esc(img.credit.author)}, ${esc(img.credit.license)}</span>` : ''}
      </button>`;
    const [lead, ...thumbs] = images;
    const data = images.map((img) => ({ src: img.src, alt: img.alt, credit: img.credit || null }));
    return `
  <div class="gallery${thumbs.length ? '' : ' single'}" data-gallery="${esc(JSON.stringify(data))}">
    ${item(lead, 0, 'gallery-lead')}${thumbs.length ? `
    <div class="gallery-thumbs">${thumbs.map((img, i) => item(img, i + 1, '')).join('')}
    </div>` : ''}
  </div>
  `;
  });

  site.registerBlock('tour-glance', (page) => {
    const pkg = page.tour;
    const departures = pkg.departureWeekdays && pkg.departureWeekdays.length
      ? listJoin(pkg.departureWeekdays.map((d) => `${WEEKDAYS[d]}s`))
      : 'Any date';
    const rows = [
      ['Duration', `${pkg.duration} days`],
      ['Stops', `${uniqueStops(pkg).length} places`],
      pkg.groupSize ? ['Group size', `Up to ${pkg.groupSize}`] : null,
      ['Departures', departures],
    ].filter(Boolean);
    return `
  <dl class="glance">
    ${rows.map(([k, v]) => `<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('\n    ')}
    <div data-price-row><dt>Price per person</dt><dd><span data-tour="${pkg.key}" data-price-format="glance"></span></dd></div>
  </dl>
  `;
  });

  site.registerBlock('tour-route', (page) => {
    const pkg = page.tour;
    const hasDays = pkg.days.length > 0;
    const points = pkg.stops.map((s) => map.project(s.lat, s.lng));
    const polyline = points.map((p) => `${p.x},${p.y}`).join(' ');
    const vb = fitViewBox(points);
    const font = Math.round(vb.w * FONT_PER_UNIT * 10) / 10;
    const dot = Math.round(vb.w * DOT_PER_UNIT * 10) / 10;
    const stopsSvg = uniqueStops(pkg).map((s) => {
      const p = map.project(s.lat, s.lng);
      const label = placeLabel(s.name, p, vb, font, dot * 1.9);
      const indexes = pkg.stops.map((o, i) => (o.name === s.name ? i : -1)).filter((i) => i >= 0).join(' ');
      return `<g class="map-stop" data-stop-indexes="${indexes}"><circle cx="${p.x}" cy="${p.y}" r="${dot}"/><text x="${label.x}" y="${label.y}">${esc(s.name)}</text></g>`;
    }).join('\n        ');
    const places = pkg.stops.map((s) => s.name);
    const svg = `
    <figure class="route-map${hasDays ? ' has-days sticky-map' : ''}" data-route-map>
      <svg viewBox="${vb.x} ${vb.y} ${vb.w} ${vb.h}" role="img" aria-labelledby="mapTitle mapDesc" style="--map-font:${font}px; --map-dot:${dot}px">
        <title id="mapTitle">Route map of Namibia</title>
        <desc id="mapDesc">${esc(places.join(', then '))}.</desc>
        <clipPath id="mapClip"><rect x="${vb.x}" y="${vb.y}" width="${vb.w}" height="${vb.h}"/></clipPath>
        <path class="map-country" d="${OUTLINE}" clip-path="url(#mapClip)"/>
        <polyline class="map-route" points="${polyline}"/>
        ${hasDays ? `<polyline class="map-progress" points="${polyline}"/>` : ''}
        ${stopsSvg}
      </svg>
    </figure>`;

    if (!hasDays) {
      return `
      <section class="tour-section" aria-labelledby="routeTitle">
        <h2 id="routeTitle">Route overview</h2>
        ${svg}
        <ol class="stop-list">
          ${pkg.stops.map((s, i) => `<li><strong>${esc(s.name)}${i === pkg.stops.length - 1 && i > 0 && s.name === pkg.stops[0].name ? ' (return)' : ''}</strong></li>`).join('\n          ')}
        </ol>
      </section>
      `;
    }

    const mealLabel = { B: 'Breakfast', L: 'Lunch', D: 'Dinner' };
    const days = pkg.days.map((d, i) => {
      const drive = [d.driveHours ? `${d.driveHours} h drive` : '', d.km ? `${d.km} km` : ''].filter(Boolean).join(', ');
      const meals = (d.meals || '').split(',').map((m) => m.trim()).filter((m) => mealLabel[m]);
      const facts = [
        d.overnight ? `<span>${icon('bed')}Overnight: ${esc(d.overnight)}</span>` : '',
        meals.length ? `<span>${icon('meal')}${meals.map((m) => mealLabel[m]).join(', ')}</span>` : '',
      ].join('');
      return `
          <details class="day" data-stop-index="${d.stopIndex != null ? d.stopIndex : ''}"${i === 0 ? ' open' : ''}>
            <summary><span class="day-num">Day ${d.day}</span><span><span class="day-title">${esc(d.title || '')}</span>${drive ? `<br><span class="day-drive">${esc(drive)}</span>` : ''}</span>${icon('caret')}</summary>
            <div class="day-body">
              ${facts ? `<p class="day-facts">${facts}</p>` : ''}
              ${d.body ? `<p>${esc(d.body)}</p>` : ''}
            </div>
          </details>`;
    }).join('');
    return `
      <section class="tour-section" aria-labelledby="routeTitle">
        <h2 id="routeTitle">Route and itinerary</h2>
        ${svg}
        <div class="itinerary">${days}
        </div>
      </section>
      `;
  });

  site.registerBlock('tour-highlights', (page) => `
      <section class="tour-section" aria-labelledby="highlightsTitle">
        <h2 id="highlightsTitle">Highlights</h2>
        <ul class="chip-list">${page.tour.highlights.map((h) => `<li class="chip">${esc(h)}</li>`).join('')}</ul>
      </section>
      `);

  site.registerBlock('tour-checklist', (page) => {
    const { inclusions, exclusions } = page.tour;
    if (!inclusions.length && !exclusions.length) return '';
    const col = (title, items, cls, ic) => (items.length ? `
          <div class="checklist ${cls}">
            <h3>${title}</h3>
            <ul>${items.map((t) => `<li>${icon(ic)}<span>${esc(t)}</span></li>`).join('')}</ul>
          </div>` : '');
    return `
      <section class="tour-section" aria-labelledby="inclTitle">
        <h2 id="inclTitle">What's included</h2>
        <div class="checklist-cols">${col('Included', inclusions, 'incl', 'check')}${col('Not included', exclusions, 'excl', 'cross')}
        </div>
      </section>
      `;
  });

  site.registerBlock('tour-good-to-know', (page) => {
    const items = page.tour.goodToKnow || [];
    if (!items.length) return '';
    return `
      <section class="tour-section" aria-labelledby="gtkTitle">
        <h2 id="gtkTitle">Good to know</h2>
        <ul class="good-to-know">${items.map((t) => `<li>${esc(t)}</li>`).join('')}</ul>
      </section>
      `;
  });

  site.registerBlock('tour-form', (page) => {
    const pkg = page.tour;
    const max = pkg.groupSize || 12;
    return `
        <form class="tour-form" id="tourForm" data-booking-form="tour" data-service="tour" action="contact.html" novalidate
              data-max-pax="${max}">
          <input type="hidden" data-field="route" data-label="Route" value="${esc(pkg.name)}">
          <div class="field-group">
            <label for="tp-date">Departure date</label>
            <input id="tp-date" type="date" data-field="date" data-label="Date" required data-error="Choose a departure date">
          </div>
          <div class="field-group stepper-group">
            <span class="field-label" id="tp-pax-label">Travelers</span>
            <div class="stepper" role="group" aria-labelledby="tp-pax-label">
              <button type="button" data-step="-1" aria-label="Remove a traveler">${icon('minus')}</button>
              <output id="tp-pax-out" aria-live="polite" aria-labelledby="tp-pax-label">2</output>
              <button type="button" data-step="1" aria-label="Add a traveler">${icon('plus')}</button>
            </div>
            <input type="hidden" id="tp-pax" data-field="pax" data-label="Travelers" value="2">
          </div>
          <div class="panel-total" data-price-row>
            <span class="total-label">Total for <span data-pax-count>2</span> travelers</span>
            <div class="total-amount" id="tourTotal" aria-live="polite"></div>
            <p class="total-note" id="tourTotalNote"></p>
          </div>
          <div class="panel-actions">
            <button type="submit" class="btn btn-primary btn-block">Check availability</button>
            <a class="btn btn-secondary btn-block" id="tourWhatsapp" href="https://wa.me/${site.SITE_CONFIG.whatsappNumber}" target="_blank" rel="noopener">${icon('whatsapp')}Ask on WhatsApp</a>
          </div>
        </form>
        `;
  });
}

// ---------------------------------------------------------------- build
function tourPage(pkg) {
  const file = tourFile(pkg);
  const page = {
    file,
    nav: 'tours',
    sub: file,
    header: 'on-light',
    actionBar: false,
    title: `${pkg.name} | ${BRAND}`,
    ogImage: pkg.image.src,
    ogType: 'article',
    tour: pkg,
  };
  page.description = describe(pkg);
  return page;
}

function build() {
  registerTourBlocks();
  const written = [];
  site.tourPackages().filter((pkg) => pkg.key !== 'custom').forEach((pkg) => {
    const page = tourPage(pkg);
    const html = TEMPLATE
      .replace(/\{\{key\}\}/g, pkg.key)
      .replace(/\{\{name\}\}/g, esc(pkg.name))
      .replace(/\{\{route\}\}/g, esc(pkg.route));
    const out = `${GENERATED_NOTE}\n${processImages(site.applyBlocks(html, page))}`;
    fs.writeFileSync(path.join(ROOT, page.file), out);
    written.push(page.file);
  });

  const urls = [...site.PAGES.map((p) => p.file), ...written]
    .map((file) => `  <url><loc>${site.pageUrl(file)}</loc></url>`).join('\n');
  fs.writeFileSync(path.join(ROOT, 'sitemap.xml'),
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`);
  console.log(`build-tours: wrote ${written.join(', ')} and sitemap.xml.`);
}

build();
